GET http://localhost:5000/geturl?filename=wired.jpg

###
#

# POST https://kauth.kakao.com/oauth/token
# Content-Type: application/x-www-form-urlencoded

# grant_type='authorization_code'&
# client_id='c8d33bf4313176a36bbdd523ec16d9cf'&
# redirect_uri='http://localhost:5000/kakao.html'&
# code='oTpD2Bao2wHYnmRfOAJpZR_j_cMBWOuFC7RvWy6Ly3Nwh7KKJYkeYMg32j7egVRUA-fQHAopyNgAAAF77V6ASQ'

####
##

GET https://kapi.kakao.com/v2/user/me
Authorization: Bearer FF_mKYvGpj76kgJse1ktacKs3muchHO1IIJXhQo9dZsAAAF77aZQ-Q

####
GET http://localhost:5000/kakao_profile?token=FF_mKYvGpj76kgJse1ktacKs3muchHO1IIJXhQo9dZsAAAF77aZQ

###
GET http://localhost:3000/users/kakao_profile/DNliv7V6cz1s0HADcJIGOBNOqqI6JCotkybTQQo9dVwAAAF8MFxeCg


#####
##
curl -v -X POST "https://kauth.kakao.com/oauth/token" \
 -H "Content-Type: application/x-www-form-urlencoded" \
 -d "grant_type=authorization_code" \
 -d "client_id=c8d33bf4313176a36bbdd523ec16d9cf" \
 --data-urlencode "redirect_uri=http://localhost:5000/kakao.html" \
 -d "code=QCm8IPtLVP6lTYyoJ_wBFuK1nsnjz2vuZo1aqX2KmtaUbVC6YAbbt5U6MPLgACdFtWOpuwo9dVsAAAF77dEcEQ"